import { describe, it, expect } from 'vitest';
import { ConversationRecordSchema } from '../lib/schemas';
import { ConversationSchema, TimelineEventSchema } from '@howicc/schemas';
import type { Conversation } from '@howicc/schemas';

describe('Schema Alignment: CLI ↔ App', () => {
  it('should accept CLI-generated conversation in app schema', () => {
    // Simulate a conversation generated by CLI
    const cliConversation: Conversation = {
      id: 'test-session',
      title: 'Test Conversation',
      project: '/test/project',
      gitBranch: 'main',
      createdAt: '2024-01-01T10:00:00.000Z',
      updatedAt: '2024-01-01T10:05:00.000Z',
      version: '1.0.0',
      timeline: [
        {
          id: 'user-1',
          type: 'user_prompt',
          timestamp: '2024-01-01T10:00:00.000Z',
          content: 'Hello, can you help me?',
        },
        {
          id: 'assistant-1',
          type: 'assistant_turn',
          timestamp: '2024-01-01T10:00:01.000Z',
          model: 'claude-sonnet-4',
          stopReason: 'end_turn',
          content: [
            {
              type: 'text_block',
              text: 'I can help you!',
            },
          ],
        },
        {
          id: 'tool-result-1',
          type: 'tool_result',
          timestamp: '2024-01-01T10:00:02.000Z',
          toolCallId: 'tool-1',
          toolName: 'Edit',
          status: 'success',
          content: 'File edited successfully',
          structuredContent: {
            type: 'file_edit',
            oldPath: 'src/test.ts',
            diff: '--- a/src/test.ts\n+++ b/src/test.ts\n@@ -1,1 +1,2 @@\n-old\n+new\n+more',
          },
          isError: false,
        },
      ],
    };

    // Validate with CLI schema
    const cliResult = ConversationSchema.safeParse(cliConversation);
    expect(cliResult.success).toBe(true);

    // Convert to app format (as it would come from PocketBase)
    const appRecord = {
      id: cliConversation.id,
      collectionId: 'conversations',
      collectionName: 'conversations',
      created: cliConversation.createdAt,
      updated: cliConversation.updatedAt,
      title: cliConversation.title,
      slug: 'test-conversation',
      source: 'claude',
      status: 'published' as const,
      visibility: 'public' as const,
      timeline: cliConversation.timeline,
    };

    // Validate with app schema
    const appResult = ConversationRecordSchema.safeParse(appRecord);
    if (!appResult.success) {
      console.error('App schema validation errors:', JSON.stringify(appResult.error.format(), null, 2));
    }
    expect(appResult.success).toBe(true);
  });

  it('should validate timeline events with structured content', () => {
    const timelineEvents = [
      {
        id: 'tool-1',
        type: 'tool_result' as const,
        timestamp: '2024-01-01T10:00:00.000Z',
        toolCallId: 'call-1',
        toolName: 'Edit',
        status: 'success' as const,
        content: 'Legacy content',
        structuredContent: {
          type: 'file_edit' as const,
          oldPath: 'src/test.ts',
          diff: '--- a/src/test.ts\n+++ b/src/test.ts\n@@ -1,1 +1,1 @@\n-old\n+new',
        },
        isError: false,
      },
      {
        id: 'tool-2',
        type: 'tool_result' as const,
        timestamp: '2024-01-01T10:00:01.000Z',
        toolCallId: 'call-2',
        toolName: 'Bash',
        status: 'success' as const,
        content: 'Command output',
        structuredContent: {
          type: 'command' as const,
          command: 'git status',
          stdout: 'On branch main',
          exitCode: 0,
        },
        isError: false,
      },
      {
        id: 'tool-3',
        type: 'tool_result' as const,
        timestamp: '2024-01-01T10:00:02.000Z',
        toolCallId: 'call-3',
        toolName: 'TodoWrite',
        status: 'success' as const,
        content: 'TODO updated',
        structuredContent: {
          type: 'todo' as const,
          oldTodos: [],
          newTodos: [{ id: '1', content: 'Task 1' }],
        },
        isError: false,
      },
    ];

    // Validate each event
    for (const event of timelineEvents) {
      const result = TimelineEventSchema.safeParse(event);
      if (!result.success) {
        console.error('Event validation error:', JSON.stringify(result.error.format(), null, 2));
      }
      expect(result.success).toBe(true);
    }
  });

  it('should handle backward compatibility with legacy content-only tool results', () => {
    const legacyEvent = {
      id: 'tool-legacy',
      type: 'tool_result' as const,
      timestamp: '2024-01-01T10:00:00.000Z',
      toolCallId: 'call-1',
      toolName: 'Read',
      status: 'success' as const,
      content: 'File contents here',
      // No structuredContent - legacy format
      isError: false,
    };

    const result = TimelineEventSchema.safeParse(legacyEvent);
    expect(result.success).toBe(true);
  });
});
